config/routes.rb
Wotdashboard::Application.routes.draw do

  resources :reports

  match "funnels" => "funnels#index", :as => :funnels
  match "funnels/normal/:start/:end/:traffic_type" => "funnels#get_data_normal", :as => :funnels_get_data_normal
  match "funnels/adquisition/:start/:end/:traffic_type" => "funnels#get_data_adquisition", :as => :funnels_get_data_adquisition
  post "funnels/save_report" => "funnels#save_report"
  post "funnels/update_report" => "funnels#update_report"
  get "funnels/get_dates" => "funnels#get_dates"
  post "results" => "home#results", :as => :home_results
  match "preview" => "funnels#preview", :as => :funnels_preview
  match "process/:data_file" => "funnels#process_file", :as => :funnels_process_file

  match ":id/:title" => "home#get_report", :as => :get_report, :constraints => {:id => /[0-9]+/}

  devise_for :users, :controllers => {:sessions => 'devise/sessions'}, :skip => [:sessions] do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root :to => 'home#index'

end

app/views/shared/_footer.html.haml
%div{:class=> "footer #{controller.controller_name}"}
	%p &copy; WoT Dashboard #{Date.today.year}

app/views/shared/_form_search_report.html.haml
%h5.soft Find reports
=form_for(:user, :url => home_results_path) do |f|
	%p= f.text_field :title, :class => 'span3'
	%p= f.submit 'Go', :class => 'btn small primary'

app/views/shared/_header.html.haml
%div{:class => 'topbar', :"data-dropdown" => 'dropdown'}
  %div{:class => 'topbar-inner'}
    %div{:class => 'container-fluid'}
      %h3
        =link_to image_tag("wot-logo-header.png", :border => 0, :style => 'margin-right: 15px'), root_path, :style => 'margin: 0px; padding: 0px'
      -if user_signed_in?
        %nav
          %ul{:class => 'nav'}
            %li{:class => check_item_active(request.url, '')}= link_to 'Home', root_path
            - if current_user.admin
              %li{:class => check_item_active(request.url, 'reports')}= link_to 'Reports', reports_path
              -#%li{:class => check_item_active(request.url, 'funnels')}=# link_to 'Add files', funnels_path
        %nav
          %ul{:class => 'nav secondary-nav'}
            %li{:class => 'dropdown'}
              = link_to current_user.username.capitalize, '#', :class => 'dropdown-toggle'
              %ul{:class => 'dropdown-menu'}
                %li= link_to 'Preferences', '#'
                %li{:class => 'divider'}
                %li= link_to 'Logout', destroy_user_session_path

app/views/shared/_recent_reports.html.haml
%h5.soft Recent reports
-if @last_reports.empty?
  %p No reports added
-else
  %ul
    - @last_reports.each do |report|
      %li
        = link_to report.title, get_report_path(report.id, report.title_slugize)