config/routes.rb
Wotdashboard::Application.routes.draw do

  resources :reports

  match "funnels" => "funnels#index", :as => :funnels
  match "funnels/normal/:start/:end/:traffic_type" => "funnels#get_data_normal", :as => :funnels_get_data_normal
  match "funnels/adquisition/:start/:end/:traffic_type" => "funnels#get_data_adquisition", :as => :funnels_get_data_adquisition
  post "funnels/save_report" => "funnels#save_report"
  post "funnels/update_report" => "funnels#update_report"
  get "funnels/get_dates" => "funnels#get_dates"
  post "results" => "home#results", :as => :home_results
  match "preview" => "funnels#preview", :as => :funnels_preview
  match "process/:data_file" => "funnels#process_file", :as => :funnels_process_file

  match ":id/:title" => "home#get_report", :as => :get_report, :constraints => {:id => /[0-9]+/}

  devise_for :users, :controllers => {:sessions => 'devise/sessions'}, :skip => [:sessions] do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root :to => 'home#index'

end

app/models/funnel.rb
class Funnel < ActiveRecord::Base
  belongs_to :report
  attr_accessible :traffic_type,  :confirmed, :logged_in, :first_battle, :first_upgrade, :tank_purchase, :start_date, :end_date

  scope :ads, where(traffic_type: "Ads").order("start_date asc")
  scope :direct, where(traffic_type: "Direct").order("start_date asc")
end

app/controllers/funnels_controller.rb
require 'wot/process_file'
require "base64"


class FunnelsController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def preview
    unless params[:funnels].nil?
      begin

        uploader = DataUploader.new
        uploader.store!(params[:funnels][:file])

        logger.warn "uploader #{uploader.inspect}"
        @funnels = Wot::ProcessFile.load_data((params[:funnels][:file].tempfile).to_path, true)
        unless @funnels.empty?
          @data_file = Base64.encode64(params[:funnels][:file].original_filename)
        end
      rescue Exception => e
        flash[:error] = e.message
        redirect_to funnels_path
      end
    else
      flash[:error] = "Data file is empty"
      redirect_to funnels_path
    end
  end

  def process_file
    unless params[:data_file].nil?
      begin
        #Todo: we'll probably store this in amazon s3'

        dir_store = (Rails.env != 'development')?  "/data/" : "public/data/"
        funnels = Wot::ProcessFile.load_data(dir_store + Base64.decode64(params[:data_file]))
        if funnels
          Wot::ProcessFile.create_funnels(funnels[:ads], "Ads")
          Wot::ProcessFile.create_funnels(funnels[:direct], "Direct")
          flash[:notice] = "Your data file is saved"
          redirect_to funnels_path
        end

      rescue Exception => e
        flash[:error] = e.message
        redirect_to funnels_path
      end
    else
      flash[:error] = "An unexpected error occurred, please try again"
      redirect_to funnels_path
    end
  end

  def get_data_normal
    @funnel_data = Funnel.select("id, traffic_type, confirmed, logged_in, first_battle, first_upgrade, tank_purchase, start_date").where(:start_date => (params[:start].to_date)..(params[:end].to_date), :traffic_type => params[:traffic_type])
    respond_to do |format|
      format.json { render :json => @funnel_data }
    end
  end

  def get_data_adquisition
    @funnel_data = Funnel.select("traffic_type, sum(confirmed) AS confirmed, sum(logged_in) AS logged_in, sum(first_battle) AS first_battle, sum(first_upgrade) AS first_upgrade, sum(tank_purchase) AS tank_purchase").where(:start_date => (params[:start].to_date)..(params[:end].to_date), :traffic_type => params[:traffic_type]).group('traffic_type')
    respond_to do |format|
      format.json { render :json => @funnel_data }
    end
  end
  
  def get_dates
    last_date = Funnel.select("start_date").order('start_date DESC').limit(1)
    if last_date.length == 1
      week_dates = []
      last_date[0].start_date.downto(last_date[0].start_date << 2) do |temp_date|
        if temp_date.saturday? && week_dates.length < 4
          week_dates << {starts: temp_date - 6, ends: temp_date}
        end
      end
      render :json => {dates: week_dates}
    else
      render :json => {last_date: 0}
    end
    
  end

  def save_report
    graph = Graphic.where(:chart_type => params[:report][:chart_type])
    report = Report.new(params[:report])
    report.graphic_id = graph
    report.user_id = current_user.id
    report.is_autogenerated = false
    if report.save
      render :json => {status: 200, id: report.id, title_slug: report.title_slugize}
    else
      render :json => {status: 101, error: report.errors}
    end
  end

  def update_report
    graph = Graphic.where(:chart_type => params[:report][:chart_type])
    report = Report.find(params[:report][:id])
    params[:report][:graphic_id] = graph[0].id

    if report.update_attributes(params[:report])
      render :json => {status: 200}
    else
      render :json => {status: 101, error: report.errors}
      pry.binding
    end
  end
end

app/helpers/funnels_helper.rb
module FunnelsHelper
end

app/views/funnels/_direct_funnels.html.haml
%h4 Direct Traffic
%table
    %thead
        %tr
            %th Week
            -#%th Start Date
            -#%th End Date
            %th Confirmed
            %th Logged In
            %th First Battle
            %th First Upgrade
            %th Tank Purchase
        - direct_funnels.each do |row|
            %tr
                %td.week= row[:week]
                -#%td= row[:start_date]
                -#%td= row[:end_date]
                %td= number_with_delimiter(row[:confirmed])
                %td= number_with_delimiter(row[:logged_in])
                %td= number_with_delimiter(row[:first_battle])
                %td= number_with_delimiter(row[:first_upgrade])
                %td= number_with_delimiter(row[:tank_purchase])

app/views/funnels/_list_funnels.html.haml
- totals = funnels.last[:totals]
%h4=title
%table
    %thead
        %tr
            %th Week
            %th Confirmed
            %th Logged In
            %th First Battle
            %th First Upgrade
            %th Tank Purchase
    %tbody
        - funnels[0...funnels.size - 1].each do |row|
            %tr
                %td.week= row[:week]
                %td= number_with_delimiter(row[:confirmed])
                %td= number_with_delimiter(row[:logged_in])
                %td= number_with_delimiter(row[:first_battle])
                %td= number_with_delimiter(row[:first_upgrade])
                %td= number_with_delimiter(row[:tank_purchase])
    %tfoot
        %tr
            %td.totals Totals
            %td=number_with_delimiter(totals[:confirmed])
            %td=number_with_delimiter(totals[:logged_in])
            %td=number_with_delimiter(totals[:first_battle])
            %td=number_with_delimiter(totals[:first_upgrade])
            %td=number_with_delimiter(totals[:tank_purchase])

app/views/funnels/_sidebar.html.haml
%div.well
    %h5 Related Reports
    %ul
        %li
            %a{:href=> "#"} Report 3
        %li
            %a{:href=> "#"} Report 14
        %li
            %a{:href=> "#"} Report 2

app/views/funnels/index.html.haml
%div.sidebar

%div.content
	- flash.each do |name, msg|
		= show_flash name, msg
	%div.page-header
		%h2
			Add Files
			%small= "Here you can add files data in the app #{Rails.env}"
	%div.row
		%div.span12
			= form_for :funnels, {:url => funnels_preview_path} do |f|
				%fieldset
					%legend You can add CSV or XLS formats
					%div.clearfix
						%label{:for => 'file'} Data file
						%div.input
							= f.file_field :file, :class => 'xInput'
					%div.well{:style => 'padding: 14px 19px;text-align:center;'}
						= f.submit 'Add', :class => 'btn primary'
	%div.row
		%div.span16
			%h4
				Recomendations
				%span.label.important Important
			%ul
				%li You have to verify that you have the correct format
				%li Remove blank lines between corrects lines with data
				%li if you have any questions, consult with a support agent

app/views/funnels/preview.html.haml
%div.sidebar
=# render 'sidebar'
%div.content
	- flash.each do |name, msg|
		= show_flash name, msg
	%div.page-header
		%h2
			Add Files
			%small Preview
	%div.row
		%div.span12
			= render :partial=> 'list_funnels', :locals => {:funnels => @funnels[:direct], :title => 'Direct Traffic'}
			= render :partial=> 'list_funnels', :locals => {:funnels => @funnels[:ads], :title =>'With Promo Actions/Ads'}
			%div.well{:style => 'padding: 14px 19px;text-align:center;'}
				%div.action
					= link_to 'Cancel', funnels_path, :class => 'btn cancel'
					= link_to 'Ok', funnels_process_file_path(@data_file), :class => 'btn primary'