config/routes.rb
Wotdashboard::Application.routes.draw do

  resources :reports

  match "funnels" => "funnels#index", :as => :funnels
  match "funnels/normal/:start/:end/:traffic_type" => "funnels#get_data_normal", :as => :funnels_get_data_normal
  match "funnels/adquisition/:start/:end/:traffic_type" => "funnels#get_data_adquisition", :as => :funnels_get_data_adquisition
  post "funnels/save_report" => "funnels#save_report"
  post "funnels/update_report" => "funnels#update_report"
  get "funnels/get_dates" => "funnels#get_dates"
  post "results" => "home#results", :as => :home_results
  match "preview" => "funnels#preview", :as => :funnels_preview
  match "process/:data_file" => "funnels#process_file", :as => :funnels_process_file

  match ":id/:title" => "home#get_report", :as => :get_report, :constraints => {:id => /[0-9]+/}

  devise_for :users, :controllers => {:sessions => 'devise/sessions'}, :skip => [:sessions] do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root :to => 'home#index'

end

app/models/report.rb
require 'iconv'

class Report < ActiveRecord::Base
  belongs_to :graphic
  has_many :funnels

  attr_accessible :starts_date, :ends_date, :title, :note, :data, :graphic_id
  validates_presence_of :starts_date, :ends_date, :title
  validates_uniqueness_of :title

  mount_uploader :data, DataUploader



  after_create :set_default_graphic

  def title_slugize(slug = '-')
    sluged = Iconv.iconv('ascii//TRANSLIT//IGNORE', 'utf-8', self.title).to_s
    sluged.gsub!(/&/, 'and')
    sluged.gsub!(/[^\w_\-#{Regexp.escape(slug)}]+/i, slug)
    sluged.gsub!(/#{slug}{2,}/i, slug)
    sluged.gsub!(/^#{slug}|#{slug}$/i, '')
    URI.escape(sluged.downcase, /[^\w_+-]/i)
  end

  def set_default_graphic
    self.graphic = Graphic.find_by_chart_type("adquisition")
  end

end

app/controllers/reports_controller.rb
require 'wot/process_file'
class ReportsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @reports = Report.order("created_at desc").limit(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  def show
    @report = Report.find(params[:id])
    @ads_funnels = Funnel.where("start_date>=? and end_date<=?", @report.starts_date, @report.ends_date).where(traffic_type: "Ads").order("start_date ASC")
    @direct_funnels = Funnel.where("start_date>=? and end_date<=?", @report.starts_date, @report.ends_date).where(traffic_type: "Direct").order("start_date ASC")
    respond_to do |format|
      if !@ads_funnels.empty? &&
          !@direct_funnels.empty?
        format.html # show.html.erb
        format.json { render json: @report }
      else
        flash[:notice] = "Couldn't find funnels in that range'"
        render 'index'
      end
    end
  end

  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  def edit
    @report = Report.find(params[:id])
  end

  def create
    @report = Report.new(params[:report])
    if params[:report] && params[:report][:data] &&
       (params[:report][:starts_date].nil? || params[:report][:ends_date].nil?)

      @funnels = Wot::ProcessFile.load_data((params[:report][:data].tempfile).to_path)

      unless @funnels.empty?
        values = {first_week: @funnels[:ads][0][:week],
                  last_week: @funnels[:ads][@funnels[:ads].length - 2][:week]}

        starts_date_report = Wot::ProcessFile.check_week(values[:first_week])[:start]
        ends_date_report = Wot::ProcessFile.check_week(values[:last_week])[:end]

        @report.starts_date = Date.parse(starts_date_report.to_s)
        @report.ends_date = Date.parse(ends_date_report.to_s)
        @report.title = "Generated report from #{starts_date_report.to_s} to #{ends_date_report.to_s} "
        @report.funnels << Wot::ProcessFile.create_funnels(@funnels[:ads], "Ads")
        @report.funnels << Wot::ProcessFile.create_funnels(@funnels[:direct], "Direct")

      end
    end

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :ok }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= form_for @report do |f|
  -if @report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      %ul
        - @report.errors.full_messages.each do |msg|
          %li= msg
  %div.row
    %fieldset
      = f.label :title
      .input
        = f.text_field :title, :class => 'span9'
        %span.help-block
          %strong Note:
          By default will be "Generated report from date1(dd/mm) to date2(dd/mm)"
  %div.row
    %fieldset
      = f.label :note
      .input
        = f.text_area :note, :class => 'span9'
        %span.help-block
          Add here any additional note
  -if @report.new_record?
    %div.row
      %div.span12
        %fieldset
          %legend You can add CSV or XLS formats
          %div.clearfix
            %label{:for => 'data'} Data file
            %div.input
              = f.file_field :data
          %div.well{:style => 'padding: 14px 19px;text-align:center;'}
            = f.submit 'Add', :class => 'btn primary'

    %div.row
      %div.span16
        %h4
          Recommendations
          %span.label.important Important
        %ul
          %li You have to verify that you have the correct format
          %li Remove blank lines between corrects lines with data
          %li if you have any questions, consult with a support agent

app/views/reports/_funnels.html.haml
-# totals = funnels.last[:totals]
%h4=title
%table
    %thead
        %tr
            %th Week
            %th Confirmed
            %th Logged In
            %th First Battle
            %th First Upgrade
            %th Tank Purchase
    %tbody
        - funnels.each do |funnel|
            %tr
                %td.week
                    ="#{funnel.start_date.strftime("%e %b")} - #{funnel.end_date.strftime("%e %b")} "
                %td= number_with_delimiter(funnel.confirmed)
                %td= number_with_delimiter(funnel.logged_in)
                %td= number_with_delimiter(funnel.first_battle)
                %td= number_with_delimiter(funnel.first_upgrade)
                %td= number_with_delimiter(funnel.tank_purchase)
    %tfoot
        %tr
            %td.totals Totals
            %td=number_with_delimiter(funnels.sum(:confirmed))
            %td=number_with_delimiter(funnels.sum(:logged_in))
            %td=number_with_delimiter(funnels.sum(:first_battle))
            %td=number_with_delimiter(funnels.sum(:first_upgrade))
            %td=number_with_delimiter(funnels.sum(:tank_purchase))

app/views/reports/edit.html.haml
%div.sidebar

%div.content
  %p#notice= notice
  - flash.each do |name, msg|
    = show_flash name, msg
  %div.page-header
    %h2
      Reports
      %small= "Editing"
  %div.row
    %div.span12
      = render 'form'

      = link_to 'Show', @report
      \|
      = link_to 'Back', reports_path

app/views/reports/index.html.haml
%div.content
	%div.page-header
		%h2
			Reports
			%small= "Most recents"
	%table.zebra-striped
		%thead
			%tr
				%th Starts date
				%th Ends date
				%th Title
				%th Note
				-#%th Filename
				%th
				%th
				%th
		%tbody
			- @reports.each do |report|
				%tr
					%td= report.starts_date
					%td= report.ends_date
					%td= report.title
					%td= report.note
					-#%td=# report.data
					%td= link_to 'Show', report, class: 'btn secondary'
					%td= link_to 'Edit', edit_report_path(report), class: 'btn secondary'
					%td= link_to 'Destroy', report, class: 'btn danger', :confirm => 'Are you sure?', :method => :delete
	%div
	%br= link_to 'Add Report', new_report_path, class: 'btn primary'

app/views/reports/new.html.haml
%div.sidebar
%div.content
  - flash.each do |name, msg|
    = show_flash name, msg
  %div.page-header
    %h2
      Add Files
      %small= "Here you can add files data in the app #{Rails.env}"
  %div.row
    %div.span12
      = render 'form'
  %fieldset
    = link_to 'Back', reports_path

app/views/reports/show.html.haml
%div.sidebar

%div.content
  - flash.each do |name, msg|
    = show_flash name, msg
  %div.page-header
    %h2
      Report
  %div.row
    %div.span12
      %fieldset
        %p
          %b Title:
          = @report.title
        %p
          %b From
          =@report.starts_date
          %b To
          =@report.ends_date
        %p
          %b Note:
          = @report.note
        -#%p
        -#  %b Filename:
        -#  =# @report.data
      %fieldset
        = render :partial=> 'funnels', :locals => {:funnels => @direct_funnels, :title => 'Direct Traffic'}
        = render :partial=> 'funnels', :locals => {:funnels => @ads_funnels, :title => 'With Promo Actions/Ads'}

      %fieldset
        = link_to 'Edit', edit_report_path(@report)
        \|
        = link_to 'Back', reports_path